version: '3.1'
services:
  back:
    image: back
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    working_dir: /traveling_girls_api/app
    volumes:
      - .:/traveling_girls_api
    tmpfs:
      - /traveling_girls_api/app/tmp
    networks:
      - shared

networks:
  shared: 
    external:
      name: shared