default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: secure
  host: mysql
  port: 3306

development:
  <<: *default
  database: traveling_girls_development

test:
  <<: *default
  database: traveling_girls_development
